name: dart_envirofacts
description: A dart package for accessing the EPA's envirofacts API
version: 0.1.0
author: Joe Diragi <joyod3@gmail.com>
homepage: https://jdiggity.me/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+1
  dart_json: ^1.0.0

dev_dependencies:
  test: ^1.6.1