import 'handlers/network.dart';

/// The type of this SEMS site
enum SEMS_TYPE {
    /// This site is active and needs help!
    active,
    /// This site has been archived
    archived
}

/// Provides access functions to all data provided by the EPA's Superfund
/// Enterprise Management System. More info can be found at the model page
/// [here](https://www.epa.gov/enviro/sems-model).
class SEMS {
  /// The type of this site (one of: SEMS_TYPE.ACTIVE/ARCHIVED)
  SEMS_TYPE type;
  /// Is this facility a federal entity?
  bool ff;
  /// The latitude value of the GPS coordinates
  double latitude;
  /// The longitude value of the GPS coordinates
  double longitude;
  /// The description of the code that ids the status of a non-npl site
  double nonNplStatus;
  /// Is this site on the national priorities list?
  bool npl;
  /// The name of the city in which this site is located.
  String cityName;
  /// The name of the county in which this site is located.
  String countyName;
  /// The congressional district within which this site is located.
  String congressionalDistrict;
  /// A code that uniquely identifies this site in the EPA's database.
  String epaID;
  /// A five-digit Federal Information Processing Standard code.
  /// More information can be found [here](https://ofmpub.epa.gov/enviro/EF_METADATA_HTML.ef_metadata_page?p_column_name=SITE_FIPS_CODE&p_table_name=sems_active_sites&p_topic=sems)
  String fipsCode;
  /// A unique identifier for this site generated by SEMS at each region.
  String siteID;
  /// The legal name of this site
  String siteName;
  /// The state in which this site is located
  String stateName;
  /// The first line of the street address of this site.
  String streetAddress1;
  /// The second line of the street address
  String streetAddress2;
  /// The zipcode of this site
  String zipCode;

  /// The default constructor. gets data from API using the EPA ID
  SEMS.fromID(this.epaID) {
    
  }
}

// https://iaspub.epa.gov/enviro/ef_metadata_html.ef_metadata_table?p_table_name=dart_envirofacts_active_sites&p_topic=dart_envirofacts